# Site settings
title: |
: La linguista realista
description: "Mi chiamo Angela Brisotto, sono nata e cresciuta in Italia, ma parlo anche inglese e polacco. Di professione fornisco diversi servizi linguistici: traduzioni, revisioni, trascrizioni e lezioni di inglese. La linguista realista è uno spazio che raccoglie spunti, informazioni e curiosità sulla mia esperienza professionale e consigli realistici per chi è appassionatә di lingue."
url: "https://angelatiliatranslations.github.io/blog/"
author: "Angela Brisotto"
  name: "Angela Brisotto"
  email: "angela@tiliatranslations.it"
  url: "https://www.tiliatranslations.it/"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
